### ISSUE TITLE
Registrer to Travis CI

### ISSUE THREAD

**Issue by NathanBnm** [linux-hub-subpixel/license#5]
You recently added the `travis.yml` configuration file for Travis CI via #3 but you do not seem to be registered in Travis CI. You should register if you want to user continuous integration properly.

You can read the docs here: https://github.com/elementary/houston/wiki/Continuous%20Integration

**Comment by mirkobrombin** [comment]
I haven't studied Travis yet, thank you for the information.

**Comment by mirkobrombin** [comment]
I should have set everything up correctly.
